export const NACE_TWO_DIGIT_DESCRIPTIONS: Record<string, string> = {
  "01": "Crop and animal production, hunting and related service activities (Rev 2.1)",
  "02": "Forestry and logging",
  "03": "Fishing and aquaculture (Rev 2.1)",
  "05": "Mining of coal and lignite",
  "06": "Extraction of crude petroleum and natural gas",
  "07": "Mining of metal ores",
  "08": "Other mining and quarrying",
  "09": "Mining support service activities",
  "10": "Manufacture of food products (Rev 2.1)",
  "11": "Manufacture of beverages (Rev 2.1)",
  "12": "Manufacture of tobacco products",
  "13": "Manufacture of textiles (Rev 2.1)",
  "14": "Manufacture of wearing apparel",
  "15": "Manufacture of leather and related products of other materials (Rev 2.1)",
  "16": "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials (Rev 2.1)",
  "17": "Manufacture of paper and paper products",
  "18": "Printing and reproduction of recorded media (Rev 2.1)",
  "19": "Manufacture of coke and refined petroleum products",
  "20": "Manufacture of chemicals and chemical products (Rev 2.1)",
  "21": "Manufacture of basic pharmaceutical products and pharmaceutical preparations",
  "22": "Manufacture of rubber and plastic products (Rev 2.1)",
  "23": "Manufacture of other non-metallic mineral products (Rev 2.1)",
  "24": "Manufacture of basic metals",
  "25": "Manufacture of fabricated metal products, except machinery and equipment (Rev 2.1)",
  "26": "Manufacture of computer, electronic and optical products (Rev 2.1)",
  "27": "Manufacture of electrical equipment (Rev 2.1)",
  "28": "Manufacture of machinery and equipment n.e.c. (Rev 2.1)",
  "29": "Manufacture of motor vehicles, trailers and semi-trailers (Rev 2.1)",
  "30": "Manufacture of other transport equipment (Rev 2.1)",
  "31": "Manufacture of furniture (Rev 2.1)",
  "32": "Other manufacturing (Rev 2.1)",
  "33": "Repair, maintenance and installation of machinery and equipment (Rev 2.1)",
  "35": "Electricity, gas, steam and air conditioning supply (Rev 2.1)",
  "36": "Water collection, treatment and supply",
  "37": "Sewerage",
  "38": "Waste collection, recovery and disposal activities (Rev 2.1)",
  "39": "Remediation activities and other waste management service activities",
  "41": "Construction of residential and non-residential buildings (Rev 2.1)",
  "42": "Civil engineering (Rev 2.1)",
  "43": "Specialised construction activities (Rev 2.1)",
  "46": "Wholesale trade (Rev 2.1)",
  "47": "Retail trade (Rev 2.1)",
  "49": "Land transport and transport via pipelines (Rev 2.1)",
  "50": "Water transport",
  "51": "Air transport",
  "52": "Warehousing, storage and support activities for transportation (Rev 2.1)",
  "53": "Postal and courier activities (Rev 2.1)",
  "55": "Accommodation (Rev 2.1)",
  "56": "Food and beverage service activities (Rev 2.1)",
  "58": "Publishing activities",
  "59": "Motion picture, video and television programme production, sound recording and music publishing activities",
  "60": "Programming, broadcasting, news agency and other content distribution activities (Rev 2.1)",
  "61": "Telecommunication (Rev 2.1)",
  "62": "Computer programming, consultancy and related activities",
  "63": "Computing infrastructure, data processing, hosting and other information service activities (Rev 2.1)",
  "64": "Financial service activities, except insurance and pension funding",
  "65": "Insurance, reinsurance and pension funding, except compulsory social security",
  "66": "Activities auxiliary to financial services and insurance activities",
  "68": "Real estate activities (Rev 2.1)",
  "69": "Legal and accounting activities",
  "70": "Activities of head offices and management consultancy (Rev 2.1)",
  "71": "Architectural and engineering activities; technical testing and analysis",
  "72": "Scientific research and development",
  "73": "Activities of advertising, market research and public relations (Rev 2.1)",
  "74": "Other professional, scientific and technical activities (Rev 2.1)",
  "75": "Veterinary activities",
  "77": "Rental and leasing activities (Rev 2.1)",
  "78": "Employment activities",
  "79": "Travel agency, tour operator and other reservation service and related activities (Rev 2.1)",
  "80": "Investigation and security activities (Rev 2.1)",
  "81": "Services to buildings and landscape activities (Rev 2.1)",
  "82": "Office administrative, office support and other business support activities (Rev 2.1)",
  "84": "Public administration and defence; compulsory social security (Rev 2.1)",
  "85": "Education (Rev 2.1)",
  "86": "Human health activities (Rev 2.1)",
  "87": "Residential care activities (Rev 2.1)",
  "88": "Social work activities without accommodation (Rev 2.1)",
  "90": "Arts creation and performing arts activities (Rev 2.1)",
  "91": "Libraries, archives, museums and other cultural activities (Rev 2.1)",
  "92": "Gambling and betting activities",
  "93": "Sports activities and amusement and recreation activities (Rev 2.1)",
  "94": "Activities of membership organisations",
  "95": "Repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles (Rev 2.1)",
  "96": "Personal service activities (Rev 2.1)",
  "97": "Activities of households as employers of domestic personnel",
  "98": "Undifferentiated goods- and service-producing activities of private households for own use",
  "99": "Activities of extraterritorial organisations and bodies",
};
